Small Update to Dist Generation

diff --git a/lib/GIT-VERSION-GEN b/lib/GIT-VERSION-GEN
--- a/lib/GIT-VERSION-GEN
+++ b/lib/GIT-VERSION-GEN
@@ -42,10 +42,16 @@ sha1=$(git rev-parse HEAD) ||
 tagname=refs/benchs/$sha1
 version="$sha1 $user $date"
 
-git push "$REPOS" HEAD:$tagname 2>/dev/null || {
-    version="$version unpublished"
-    echo >&2 "GEN-VERSION: Pushing HEAD to $tagname in $REPOS failed!"
-}
+# If the exact commit used for this build carries a git tag, treat the build as published
+gittag=$(git tag --points-at HEAD 2>/dev/null | head -n 1)
+if [ -n "$gittag" ]; then
+    version="$version published under $gittag"
+else
+    git push "$REPOS" HEAD:$tagname 2>/dev/null || {
+        version="$version unpublished"
+        echo >&2 "GEN-VERSION: Pushing HEAD to $tagname in $REPOS failed!"
+    }
+fi
 
 git update-index -q --refresh
 if [ -n "$(git diff-index --name-only HEAD --)" ]; then
